sudo: required

language: bash

services:
 - docker

branches:
  only: 
    - master
    - latest
    - 1.8.8
    - 1.8.3
    - 1.8

install: 
    - docker build -t bbriggs/bukkit:1.8.3 .

script:
    - docker run -it -p 25565:25565 -v /data:/data -e EULA=true -e TRAVIS=true bbriggs/bukkit:1.8.3

after_success:
    - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD --email=$DOCKER_EMAIL 
    - docker push bbriggs/bukkit:1.8.3
